    <?php 
    
    if($_POST){
         error_log('Send CV is running!');
         
         if ( ! function_exists( 'wp_handle_upload' ) ) {
            require_once( ABSPATH . 'wp-admin/includes/file.php' );
        }
        
        
        // Hentet fra PHP dokumentasjon: http://php.net/manual/en/features.file-upload.php
        try {
    
            // Undefined | Multiple Files | $_FILES Corruption Attack
            // If this request falls under any of them, treat it invalid.
            if (
                !isset($_FILES['file']['error']) ||
                is_array($_FILES['file']['error'])
            ) {
                error_log('Invalid parameters.');
                throw new RuntimeException('Invalid parameters.');
            }

            // Check $_FILES['upfile']['error'] value.
            switch ($_FILES['file']['error']) {
                case UPLOAD_ERR_OK:
                    break;
                case UPLOAD_ERR_NO_FILE:
                    error_log('No file sent.');
                    throw new RuntimeException('No file sent.'); 
                case UPLOAD_ERR_INI_SIZE:
                case UPLOAD_ERR_FORM_SIZE:
                    error_log('Exceeded filesize limit.');
                    throw new RuntimeException('Exceeded filesize limit.');
                default:
                    error_log('Unknown errors.');
                    throw new RuntimeException('Unknown errors.');
            }

            // You should also check filesize here. 
            if ($_FILES['upfile']['size'] > 1000000) {
                 error_log('Exceeded filesize limit.');
                throw new RuntimeException('Exceeded filesize limit.');               
            }

            // You should name it uniquely.
            // DO NOT USE $_FILES['upfile']['name'] WITHOUT ANY VALIDATION !!
            // On this example, obtain safe unique name from its binary data.
            if (!move_uploaded_file(
                $_FILES['upfile']['tmp_name'],
                sprintf('./uploads/%s.%s',
                    sha1_file($_FILES['upfile']['tmp_name']),
                    $ext
                )
            )) {
                error_log('Failed to move uploaded file.');
                throw new RuntimeException('Failed to move uploaded file.');
            }

            error_log('File is uploaded successfully.');

        } catch (RuntimeException $e) {

            echo $e->getMessage();

        }
        
        
        // if($_Files){
        //       $uploadedfile = $_FILES['file'];
        
        //     error_log(var_dump($_FILES));
            
        //     $upload_overrides = array( 'test_form' => false );

        //     $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

        //     if ( $movefile && ! isset( $movefile['error'] ) ) {
        //         error_log("File is valid, and was successfully uploaded.\n");
        //         error_log(var_dump( $movefile ));
        //     } else {
        //         /**
        //         * Error generated by _wp_handle_upload()
        //         * @see _wp_handle_upload() in wp-admin/includes/file.php
        //         */
        //         error_log($movefile['error']);
        //     }
        // }
        // else {
        //     error_log('Ingen filer ble lastet opp.');
        // }
      
        
        //user posted variables
        $name = $_POST['et_pb_contact_navn_2'];
        $email = $_POST['et_pb_contact_e_post_2'];
        $message = $_POST['et_pb_contact_melding_2'];
        // $cv = $_FILES['cv']['tmp_name'];
        $human = $_POST['message_human'];
        
        error_log('POST Parametere: name = '.$name.'. email = '.$email.'. message = '.$message.'. CV = '.$ext.'. Human = '.$human);
        
        // move_uploaded_file

        //php mailer variables
        $to = get_option('admin_email');
        
        error_log('Amdin email = '.$to);
        
        $subject = "Someone sent a message from ".get_bloginfo('name');
        $headers = 'From: '.$email."\r\n".'Reply-To: '.$email."\r\n";

        if (!$human == 0) {
            if ($human != 2) {
                 error_log('not human!!!'); //not human!

            } else {

                //validate email
                if (!filter_var($email, FILTER_VALIDATE_EMAIL)) error_log('invalid email human!!!'); //email is invalid
                else //email is valid
                {
                    //validate presence of name and message
                    if (empty($name) || empty($message)) {
                        error_log('missing content!!!'); //missing content
                    } else //ready to go!
                    {
                        $attachments  = $movefile;
                        $sent = wp_mail($to, $subject, strip_tags($message), $headers, $attachments);
                        if ($sent) error_log('Message was sent!!!'); //message sent!
                        else error_log('Message was not sent!!!'); //message wasn't sent
                    }
                }
            }
        }
    }

    ?> 
    
    <?php 
    /*
    Template Name: Ledige stillinger
    */

    get_header();

    $is_page_builder_used = et_pb_is_pagebuilder_used(get_the_ID()); ?>

    <div id="main-content">

        <?php if (!$is_page_builder_used): ?>

        <div class="container">
            <div id="content-area" class="clearfix">
                <div id="left-area">

                    <?php endif; ?> <?php while (have_posts()): the_post(); ?>

                    <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>

                        <?php if (!$is_page_builder_used): ?>

                        <h1 class="main_title"><?php the_title(); ?></h1> 
<?php 
    $thumb = '';

    $width = (int) apply_filters('et_pb_index_blog_image_width', 1080);

    $height = (int) apply_filters('et_pb_index_blog_image_height', 675);
    $classtext = 'et_featured_image';
    $titletext = get_the_title();
    $thumbnail = get_thumbnail($width, $height, $classtext, $titletext, $titletext, false, 'Blogimage');
    $thumb = $thumbnail["thumb"];

    if ('on' === et_get_option('divi_page_thumbnails', 'false') && '' !== $thumb) print_thumbnail($thumb, $thumbnail["use_timthumb"], $titletext, $width, $height);
    ?> 
    <?php endif; ?>

                        <div class="entry-content">
                            <?php 
    the_content();

    if (!$is_page_builder_used) wp_link_pages(array('before' => '<div class="page-links">'.esc_html__('Pages:', 'Divi'), 'after' => '</div>'));
    
    ?>                      

                                <div class="et_pb_column et_pb_column_4_4  et_pb_column_2">

                                    <div id="et_pb_contact_form_2" class="et_pb_module et_pb_contact_form_container clearfix  et_pb_contact_form_2" data-form_unique_num="2">

                                        <div class="et_pb_contact">
                                            <form class="et_pb_contact_form clearfix" enctype="multipart/form-data" method="post" role="form" action="<?php the_permalink(); ?>" _lpchecked="1">

                                                <p class="et_pb_contact_field et_pb_contact_field_0 et_pb_contact_field_half">
                                                    <label for="et_pb_contact_navn_2" class="et_pb_contact_form_label">Navn</label>
                                                    <input type="text" id="et_pb_contact_navn_2" class="input" value="Navn" name="et_pb_contact_navn_2" data-required_mark="required" data-field_type="input" data-original_id="et_pb_contact_navn_2">
                                                </p>
                                                <p class="et_pb_contact_field et_pb_contact_field_1 et_pb_contact_field_half et_pb_contact_field_last">
                                                    <label for="et_pb_contact_e_post_2" class="et_pb_contact_form_label">E-postadresse</label>
                                                    <input type="text" id="email" class="input" value="Epost" name="et_pb_contact_e_post_2" data-required_mark="required" data-field_type="email " data-original_id="et_pb_contact_e_post_2">
                                                </p>
                                                <p class="et_pb_contact_field et_pb_contact_field_2 et_pb_contact_field_last">
                                                    <label for="et_pb_contact_melding_2" class="et_pb_contact_form_label">Kort om deg selv</label>
                                                    <textarea name="et_pb_contact_melding_2" id="et_pb_contact_melding_2" value="" class="et_pb_contact_message input" data-required_mark="required " data-field_type="text" data-original_id="et_pb_contact_melding_2">Melding</textarea>
                                                </p>
                                                <p class="et_pb_contact_field">
                                                    <label for="file" class="et_pb_contact_form_label">Last opp CV</label>                                                    
                                                    <input type="file" id="file" name="file" accept="application/pdf,application/msword">
                                                    
                                                    <!--<input type="file" id="file" name="file" accept="application/pfd,application/msword,*.docx">-->
                                                </p>

                                                <p class="et_pb_contact_field">
                                                    <label for="message_human">Human Verification: <span>*</span>
                                                        <br>
                                                        <input type="text" style="width: 60px; " id="message_human" class="input" name="message_human"> + 3 = 5</label>
                                                </p>

                                                <div class="et_contact_bottom_container ">

                                                    <button type="submit" class="et_pb_contact_submit et_pb_button et_pb_custom_button_icon" data-icon="">Send</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>



                            </div>
                            <!-- .entry-content -->

                            <?php 
    if (!$is_page_builder_used && comments_open() && 'on' === et_get_option('divi_show_pagescomments', 'false')) comments_template('', true);
    ?>

                    </article>
                    <!-- .et_pb_post -->

                    <?php endwhile; ?> <?php if (!$is_page_builder_used): ?>

                    </div>
                    <!-- #left-area -->

                    <div class="storeInfoSidebar" style="padding-left: 30px;
    float: left;
    width: 20.875%;">
                        <h3>Åpningstider Storgata</h3>
                        <hr>
                        <ul>
                            <li>Mandag: 10-18</li>
                            <li>Tirsdag: 10-18</li>
                            <li>Onsdag: 10-18</li>
                            <li>Torsdag: 10-18</li>
                            <li>Fredag: 10-18</li>
                            <li>Lørdag: 10-18</li>
                            <li>Søndag: 10-18</li>
                        </ul>
                        <br>
                        <h3>Åpningstider Sjøsiden</h3>
                        <hr>
                        <ul>
                            <li>Mandag: 10-18</li>
                            <li>Tirsdag: 10-18</li>
                            <li>Onsdag: 10-18</li>
                            <li>Torsdag: 10-18</li>
                            <li>Fredag: 10-18</li>
                            <li>Lørdag: 10-18</li>
                            <li>Søndag: 10-18</li>
                        </ul>
                        <br>
                    </div>
                    
                    <?php get_sidebar(); ?>
                </div>
                <!-- #content-area -->
            </div>
            <!-- .container -->

            <?php endif; ?>

        </div>
        <!-- #main-content -->


        <?php get_footer(); ?>